# Generated by Django 4.2.22 on 2025-07-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('pope_leo', models.BooleanField(default=False)),
                ('contact_info', models.CharField(max_length=100)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
