# Generated by Django 4.2.22 on 2025-07-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinkEditionInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested', models.BooleanField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='caporder',
            name='bust_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='caporder',
            name='font',
            field=models.CharField(default='Arial', max_length=100),
        ),
        migrations.AddField(
            model_name='caporder',
            name='font_color',
            field=models.CharField(default='white', max_length=50),
        ),
        migrations.AddField(
            model_name='caporder',
            name='le_bubu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caporder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='caporder',
            name='team',
            field=models.CharField(max_length=50),
        ),
    ]
