# Generated by Django 4.2.22 on 2025-07-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pinkeditioninterest_caporder_bust_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caporder',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
