# Generated by Django 4.2.22 on 2025-07-09 15:26

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_caporder_confirmation_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_code', models.CharField(default=api.models.generate_confirmation_code, max_length=12, unique=True)),
                ('contact_info', models.CharField(max_length=100)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='caporder',
            name='confirmation_code',
        ),
        migrations.RemoveField(
            model_name='caporder',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='caporder',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='caporder',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.ordergroup'),
        ),
    ]
