# Generated by Django 4.2.22 on 2025-07-09 18:10

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ordergroup_remove_caporder_confirmation_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapOrderGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_code', models.CharField(default=api.models.generate_confirmation_code, max_length=12, unique=True)),
                ('contact_info', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_fulfilled', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='caporder',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='caporder',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caporder',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.capordergroup'),
        ),
        migrations.DeleteModel(
            name='OrderGroup',
        ),
    ]
