# Generated by Django 4.2.22 on 2025-07-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_capordergroup_caporder_contact_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capordergroup',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
