# Generated by Django 4.2.22 on 2025-07-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_capordergroup_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='capordergroup',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
